Document: diesprachstarken
Title: Debian diesprachstarken Manual
Author: <insert document author here>
Abstract: This manual describes what diesprachstarken is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/diesprachstarken/diesprachstarken.sgml.gz

Format: postscript
Files: /usr/share/doc/diesprachstarken/diesprachstarken.ps.gz

Format: text
Files: /usr/share/doc/diesprachstarken/diesprachstarken.text.gz

Format: HTML
Index: /usr/share/doc/diesprachstarken/html/index.html
Files: /usr/share/doc/diesprachstarken/html/*.html
